; ================================
; Xdebug Development Configuration
; ================================

[xdebug]

; Mode
xdebug.mode = develop,debug,coverage

; Step debugging
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003

; Logging
xdebug.log = /var/log/xdebug/xdebug.log
xdebug.log_level = 0

; Display
xdebug.cli_color = 1
xdebug.var_display_max_depth = 10
xdebug.var_display_max_children = 256
xdebug.var_display_max_data = 1024

; Performance
xdebug.max_nesting_level = 512

; Coverage
xdebug.coverage_enable = 1
